; ============================================================
; Fichier de configuration de la simulation CFD 2D
; Format INI : clé = valeur  (commentaires avec ; ou #)
; ============================================================

[grille]
<<<<<<< HEAD
nx     = 256         ; nombre de cellules en x
ny     = 256         ; nombre de cellules en y
lx     = 0.5         ; longueur physique en x (m)
ly     = 1.0         ; longueur physique en y (m)

[fluide]
nu     = 1e-6        ; viscosité cinématique (m²/s)
rho    = 1.0         ; masse volumique (kg/m³)
U      = 0.15        ; vitesse d'entrée (m/s)
p0     = 1e5         ; pression initiale (Pa)

[cylindre]
cx     = 0.25         ; position x du centre (m)
radius = 0.2        ; rayon du cylindre (0 = pas de cylindre)

[simulation]
Tmax   = 10.0         ; temps physique final (s)
eps    = 1e-2        ; tolérance solveur pression
maxiter = 25         ; itérations max solveur pression
=======
nx     = 256        	; nombre de cellules en x
ny     = 256        	; nombre de cellules en y
lx     = 0.5        	; longueur physique en x (m)
ly     = 0.5        	; longueur physique en y (m)

[fluide]
nu     = 1e-6        	; viscosité cinématique (m²/s)
rho    = 1.0         	; masse volumique (kg/m³)
U      = 0.2         	; vitesse d'entrée (m/s)
p0     = 1e5         	; pression initiale (Pa)

[cylindre]
cx     = 0.3        	; position x du centre (m)
radius = 0.05        	; rayon du cylindre (0 = pas de cylindre)

[simulation]
Tmax   = 2.0         	; temps physique final (s)
eps    = 1e-2        	; tolérance solveur pression
maxiter = 25         	; itérations max solveur pression
>>>>>>> 9c4ea46ad118046894ec99fc641c1bfdb9119499

[export]
output_dir = output	; dossier de sortie des CSV

[affichage]
champ  = ux		; ux | uy | p | u_norm
