; ============================================================
; Fichier de configuration de la simulation CFD 2D
; Format INI : clé = valeur  (commentaires avec ; ou #)
; ============================================================

[grille]

nx     = 180         ; nombre de cellules en x
ny     = 300         ; nombre de cellules en y
lx     = 1.8         ; longueur physique en x (m)
ly     = 3.5         ; longueur physique en y (m)

[fluide]
nu     = 2e-3        ; viscosité cinématique (m²/s)
rho    = 1.0         ; masse volumique (kg/m³)
U      = 1.55         ; vitesse d'entrée (m/s)
p0     = 0.0         ; pression initiale (Pa)

[cylindre]
cx     = 0.85         ; position x du centre (m)
cy     = 0.8         ; position y du centre (m)
radius = 0.08         ; rayon du cylindre (0 = pas de cylindre)
densite= 1.2         ; densité du cylindre (kg/m³)

[simulation]
Tmax    = 800.0         ; temps physique final (s)
eps     = 1e-2        ; tolérance solveur pression
maxiter = 30         ; itérations max solveur pression

[lignes]

delta_p = 1e-2        ; tolérance sur le valeurs de pression prises pour compter dans les equipotentielles
Nb_p    = 10          ; nombre de lignes de champ sur la vitesse débutant en Y
Nb_v    = 6           ; nombre de lignes de niveau de pression


[export]
output_dir = ../../output    ; dossier de sortie des CSV

[affichage]
champ  = vort        ; ux | uy | p | u_norm | vort