; ============================================================
; Fichier de configuration de la simulation CFD 2D
; Format INI : clé = valeur  (commentaires avec ; ou #)
; ============================================================

[grille]

nx     = 64         ; nombre de cellules en x
ny     = 64         ; nombre de cellules en y
lx     = 0.5         ; longueur physique en x (m)
ly     = 0.5         ; longueur physique en y (m)

[fluide]
nu     = 1e-6        ; viscosité cinématique (m²/s)
rho    = 1.0         ; masse volumique (kg/m³)
U      = 2.0        ; vitesse d'entrée (m/s)
p0     = 1e5         ; pression initiale (Pa)

[cylindre]
cx     = 0.15         ; position x du centre (m)
radius = 0.075         ; rayon du cylindre (0 = pas de cylindre)

[simulation]
Tmax   = 40.0         ; temps physique final (s)
eps    = 1e-2        ; tolérance solveur pression
maxiter = 30         ; itérations max solveur pression


[export]
output_dir = ../../output	; dossier de sortie des CSV

[affichage]
champ  = uy		; ux | uy | p | u_norm
